configuration_version: v5
worlds:
  builders:
    plot:
      size: 96
      height: 62
      biome: minecraft:forest
      filling: stone:100
      auto_merge: true
      bedrock: true
      create_signs: true
      floor: grass_block:100
      sign_material: OAK_WALL_SIGN
    wall:
      filling: stone:100
      block_claimed: sandstone_slab:100
      height: 62
      block: stone_slab:100
      place_top_block: true
    misc_spawn_unowned: false
    road:
      block: quartz_block:100
      height: 62
      width: 7
      flags: {}
    home:
      nonmembers: side
      default: side
    schematic:
      specify_on_claim: false
      on_claim: false
      file: 'null'
      schematics: []
    economy:
      prices:
        merge: 1000
        sell: 0
        claim: 5000
      use: true
    chat:
      enabled: false
      forced: false
    limits:
      max-members: 6
    world:
      max_height: 256
      gamemode: creative
      min_height: 1
      border: false
      max_gen_height: 319
      min_gen_height: -64
    event:
      spawn:
        egg: false
        breeding: false
        custom: false
    natural_mob_spawning: false
    mob_spawner_spawning: false
    flags: {}
