stick:
  # Allows to set amount of damage on successful magic.
  # Items that cannot be damaged, like STICK, will be removed.
  # 0 means that damage will not be applied. 
  success-damage: 0
  # Allows to set amount of damage on failed magic.
  # Items that cannot be damaged, like STICK, will be removed.
  # 0 means that damage will not be applied. 
  error-damage: 0
cauldron:
  # Allows to toggle if extra ingredients should be dropped in cauldron.
  # Setting it to `true` will allow to perform magic only if items are dropped in cauldron.
  mix-in-cauldron: true
  # Allows to toggle if extra ingredients should be in correct count.
  # Setting it to `true` will fail any recipe where extras in cauldron are more then required.
  # This option works only if `mix-in-cauldron` is enabled.
  require-exact: false
  # Allows to toggle if left-overs for extra ingredients should be removed.
  # Setting it to `true` will remove all left-over ingredients that were dropped in cauldron.
  # This option works only if `mix-in-cauldron` is enabled and `require-exact` is disabled.
  remove-left-overs: false
  # Allows to toggle if items inside cauldron should be removed on failed magic.
  # Setting it to `true` will remove all items inside cauldron if magic fails.
  # This option works only if `mix-in-cauldron` is enabled.
  remove-on-fail: false
  error:
    # Allows to toggle failing should destroy the cauldron.
    # Setting it to `true` will destroy cauldron.
    # Setting it to `false` will not destroy cauldron.
    destroy-cauldron: false
    # Allows to toggle if failing recipe should display correct reason or
    # generic message about failing.
    correct-message: true
command:
  # Allows to change label for player command.
  player-command: witchery
  # Allows to change label for admin command.
  admin-command: witchery
# 
# This list stores GameModes in which CauldronWitchery addon should not work.
# To disable addon it is necessary to write its name in new line that starts with -. Example:
# disabled-gamemodes:
#  - BSkyBlock
disabled-gamemodes:
- Parkour
