#Here you can set per world scoreboards <worldname>:<filename>
#If you don't add a world here it will not have a scoreboard in that world!
#World has 2 scoreboards, it will activate them based on how they are
#listed, in this example it will first look if players can have adminboard and if
#not switch to defaultscoreboard
worlds:
  oneblock:
  - oneblockscoreboard
  skyblock:
  - skyblockscoreboard
  skygrid:
  - skygridscoreboard
  cave:
  - cavescoreboard
  acid:
  - acidscoreboard

#Now only players with the permission animatedscoreboard.test will get the scoreboard
permissions:
  adminboard: animatedscoreboard.test

placeholderapi: true
check_updates: false
debug_mode: false
enable-triggers: false
player-storage: SQLITE
force-legacy: false
hex-in-placeholders: true
