version: 0
language: en
settings:
  use-action-bar: false
  per-player-locale: true
database:
  type: sqlite
  hostname: ''
  database: ''
  username: ''
  password: ''
  prefix: ''
  properties: []
protections:
  private:
    default: true
    require-permission: false
    allows:
    - redstone
  display:
    require-permission: false
    allows:
    - redstone
    - interact
    - open
  deposit:
    require-permission: false
    allows:
    - redstone
    - interact
    - open
    - deposit
  withdrawal:
    require-permission: false
    allows:
    - redstone
    - interact
    - open
    - withdraw
  public:
    require-permission: false
    allows:
    - redstone
    - interact
    - open
    - deposit
    - withdraw
    - mount
access:
  normal:
    default: true
    require-permission: false
    allows:
    - redstone
    - interact
    - open
    - deposit
    - withdraw
    - mount
  admin:
    require-permission: true
    allows:
    - redstone
    - interact
    - open
    - deposit
    - withdraw
    - mount
    - edit
  autoclose:
    require-permission: true
    allows:
    - auto_close
sources:
  player:
    require-permission: false
  group:
    require-permission: false
  password:
    require-permission: false
  permission:
    require-permission: true
  door:
    require-permission: true
    unique: true
blocks:
  chest:
    autoProtect: private
    autoProtectPermission: true
  trapped_chest:
    autoProtect: private
    autoProtectPermission: true
  furnace:
    autoProtect: private
    autoProtectPermission: true
  blast_furnace:
    autoProtect: private
    autoProtectPermission: true
  smoker:
    autoProtect: private
    autoProtectPermission: true
  dispenser:
    autoProtect: private
    autoProtectPermission: true
  dropper:
    autoProtect: private
    autoProtectPermission: true
  barrel:
    autoProtect: private
    autoProtectPermission: true
  brewing_stand:
    autoProtect: 'false'
    autoProtectPermission: true
  composter:
    autoProtect: private
    autoProtectPermission: true
  beacon:
    autoProtect: private
    autoProtectPermission: true
  jukebox:
    autoProtect: private
    autoProtectPermission: true
  note_block:
    autoProtect: private
    autoProtectPermission: true
  lectern:
    autoProtect: private
    autoProtectPermission: true
  chiseled_bookshelf:
    autoProtect: private
    autoProtectPermission: true
  hopper:
    autoProtect: private
    autoProtectPermission: true
  decorated_pot:
    autoProtect: private
    autoProtectPermission: true
  crafter:
    autoProtect: private
    autoProtectPermission: true
  '#shulker_boxes':
    autoProtect: private
    autoProtectPermission: true
  '#anvil':
    autoProtect: private
    autoProtectPermission: true
  '#cauldrons':
    autoProtect: private
    autoProtectPermission: true
  ender_chest:
    autoProtect: public
    autoProtectPermission: true
  '#standing_signs':
    autoProtect: private
    autoProtectPermission: true
  '#wall_signs':
    autoProtect: private
    autoProtectPermission: true
  '#all_hanging_signs':
    autoProtect: private
    autoProtectPermission: true
  '#doors':
    autoProtect: private
    autoProtectPermission: true
  '#trapdoors':
    autoProtect: private
    autoProtectPermission: true
  '#fence_gates':
    autoProtect: private
    autoProtectPermission: true
  '#banners':
    autoProtect: private
    autoProtectPermission: true
  enchanting_table:
    autoProtect: private
    autoProtectPermission: true
  loom:
    autoProtect: private
    autoProtectPermission: true
  cartography_table:
    autoProtect: private
    autoProtectPermission: true
  fletching_table:
    autoProtect: private
    autoProtectPermission: true
  grindstone:
    autoProtect: private
    autoProtectPermission: true
  smithing_table:
    autoProtect: private
    autoProtectPermission: true
  stonecutter:
    autoProtect: private
    autoProtectPermission: true
  bell:
    autoProtect: private
    autoProtectPermission: true
  campfire:
    autoProtect: private
    autoProtectPermission: true
  soul_campfire:
    autoProtect: private
    autoProtectPermission: true
  bee_nest:
    autoProtect: private
    autoProtectPermission: true
  beehive:
    autoProtect: private
    autoProtectPermission: true
entities:
  armor_stand:
    autoProtect: private
    autoProtectPermission: true
  item_frame:
    autoProtect: private
    autoProtectPermission: true
  glow_item_frame:
    autoProtect: private
    autoProtectPermission: true
  painting:
    autoProtect: private
    autoProtectPermission: true
  leash_hitch:
    autoProtect: private
    autoProtectPermission: true
  chest_boat:
    autoProtect: private
    autoProtectPermission: true
  minecart_chest:
    autoProtect: private
    autoProtectPermission: true
  minecart_furnace:
    autoProtect: private
    autoProtectPermission: true
  minecart_hopper:
    autoProtect: private
    autoProtectPermission: true
doors:
  open-iron: true
  open-double: true
  close-after: 3
